version: "3"

services:
  redis:
    image: redis:alpine
    restart: always

  radium:
    restart: always
    build: ./project
    command: python radium/radium.py
    volumes:
      - ./radium/:/radium.py/
    ports:
      - "8000:8000"
    depends_on:
      - redis

#  worker:
#    restart: always
#    build:
#      context: ./project
#    volumes:
#      - ./radium:/radium
#    command: ['celery', '--workdir=./radium', '-A', 'radium', 'worker', '-B', '-E']
#    depends_on:
#      - redis